feature/implementing-ngrok-startup-script
Indicio-tech/acapy-minimal-example pull request #21
Opened 2022-11-07 16:39 UTC by anwalker293

Signed-off-by: Alexandra N. Walker <alex.walker@indicio.tech> ☀️

2022-11-15 19:34 UTC, dbluhm requested changes

2022-11-15 19:34 UTC, dbluhm commented on tunnel_endpoint.sh
> +retrieve_endpoint () {
This is more of a function that makes sure the server is ready rather than retrieving the endpoint.

2022-11-15 19:34 UTC, dbluhm commented on tunnel_endpoint.sh
> +                if ! curl -s -o /dev/null -w '%{http_code}' "${1}/url" | grep "200" > /dev/null; then
```suggestion
                if ! curl -s -o /dev/null -w '%{http_code}' "${1}" | grep "200" > /dev/null; then
```
I think we need to remove the `/url` so the function args can specify the endpoint fully and not have anything appended to it.

2022-11-15 19:34 UTC, dbluhm commented on tunnel_endpoint.sh
> +                #TODO If wait attempts exceeded and we still haven't successfully gotten an endpoint, exit with status 1
I think we should implement this TODO. In the branch where we do the waiting, we should check if current number of attempt is equal to max and then `exit 1` if it is.

2022-11-17 12:07 UTC, anwalker293 commented
@dbluhm I think this is ready to rock and roll :)

2022-11-17 14:15 UTC, dbluhm approved these changes
Looks good to me!

2022-11-17 14:15 UTC, merged