feat: update ACA-Py to 0.8.2-rc0
Indicio-tech/acapy-minimal-example pull request #47
Opened 2023-06-09 18:33 UTC by anwalker293

Tests are passing, but I wasn't able to manually test the tunnels tests. (Becoming unresponsive on my machine?) I'll ask someone on our team if they can run this, but opening PR now :)

2023-06-09 20:10 UTC, anwalker293 commented
Need to find viable image of ngrok version 3

2023-06-09 20:19 UTC, anwalker293 commented
@dbluhm

2023-07-05 18:52 UTC, anwalker293 commented
Working now! :tada:

2023-07-06 11:46 UTC, dbluhm requested changes
Let's target the official release

2023-07-06 11:46 UTC, dbluhm commented on docker-compose.tunnels.yml
> +    image: ghcr.io/hyperledger/aries-cloudagent-python:py3.9-indy-1.16.0-0.8.2-rc0
0.8.2 is now officially released :slightly_smiling_face: 
```suggestion
    image: ghcr.io/hyperledger/aries-cloudagent-python:py3.9-indy-1.16.0-0.8.2
```

2023-07-11 01:21 UTC, dbluhm approved these changes

2023-07-11 01:21 UTC, merged